"""Criando modelo

Revision ID: 386b9ba8d95b
Revises: 
Create Date: 2021-01-30 11:23:23.268270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386b9ba8d95b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acoes',
    sa.Column('id_acao', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('setor', sa.String(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_acao')
    )
    op.create_table('categoriasTransacoes',
    sa.Column('id_categoria_transacao', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria_transacao')
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_index(op.f('ix_users_id_user'), 'users', ['id_user'], unique=False)
    op.create_table('transactions',
    sa.Column('id_transacao', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_categoria_transacao', sa.Integer(), nullable=True),
    sa.Column('id_acao', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('outcome', 'income', name='enumtipo'), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_acao'], ['acoes.id_acao'], ),
    sa.ForeignKeyConstraint(['id_categoria_transacao'], ['categoriasTransacoes.id_categoria_transacao'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_transacao')
    )
    op.create_index(op.f('ix_transactions_id_transacao'), 'transactions', ['id_transacao'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id_transacao'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_users_id_user'), table_name='users')
    op.drop_table('users')
    op.drop_table('categoriasTransacoes')
    op.drop_table('acoes')
    # ### end Alembic commands ###
