"""Subindo Projeto 0002

Revision ID: 47ef0912271d
Revises: 7663c8dcfa01
Create Date: 2021-01-30 19:37:06.747264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ef0912271d'
down_revision = '7663c8dcfa01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
